# Generated by Django 5.1.7 on 2025-04-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_projectmilestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
    ]
