# Generated by Django 5.1.7 on 2025-05-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_user_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
