# Generated by Django 5.2.1 on 2025-05-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_user_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('on going', 'On Going'), ('on hold', 'On Hold'), ('completed', 'Completed')], default='planning', max_length=20),
        ),
    ]
