# Generated by Django 5.2.1 on 2026-07-16 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineModelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('stt', 'Speech to text'), ('llm', 'Language model')], max_length=16, unique=True)),
                ('model_id', models.CharField(max_length=100)),
                ('model_path', models.TextField(blank=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offline_model_settings',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('recording', 'Recording'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('building_mom', 'Building MOM'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('audio_source', models.CharField(blank=True, max_length=80)),
                ('stt_model_id', models.CharField(blank=True, max_length=100)),
                ('llm_model_id', models.CharField(blank=True, max_length=100)),
                ('final_mom', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('markdown', 'Markdown'), ('txt', 'TXT'), ('docx', 'DOCX'), ('pdf', 'PDF')], max_length=16)),
                ('file_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='projects.meeting')),
            ],
            options={
                'db_table': 'meeting_exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('chunk', 'Chunk'), ('merged', 'Merged'), ('final', 'Final')], default='chunk', max_length=16)),
                ('chunk_index', models.PositiveIntegerField(blank=True, null=True)),
                ('start_seconds', models.FloatField(blank=True, null=True)),
                ('end_seconds', models.FloatField(blank=True, null=True)),
                ('summary_markdown', models.TextField()),
                ('source_segment_start', models.PositiveIntegerField(blank=True, null=True)),
                ('source_segment_end', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='projects.meeting')),
            ],
            options={
                'db_table': 'meeting_summaries',
                'ordering': ['meeting_id', 'summary_type', 'chunk_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('text', models.TextField()),
                ('is_final', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='projects.meeting')),
            ],
            options={
                'db_table': 'transcript_segments',
                'ordering': ['meeting_id', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'sequence'), name='unique_meeting_segment_sequence')],
            },
        ),
    ]
